[package]
name = "concurrent"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["rlib"]
#crate-type = ["dylib"]

[dependencies]
parking_lot = "0.11.1"

[profile.bench]
debug = 0
codegen-units = 1