[package]
name = "concurrent"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["rlib", "dylib"]

[dependencies]
rustc-hash = "1.1.0"
parking_lot = "0.11.1"

[profile.bench]
debug = 0
codegen-units = 1