[package]
name = "horde"
version = "0.0.1"
edition = "2018"
description = "a horde of threads"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["rlib"]
#crate-type = ["dylib"]

[dependencies]
parking_lot = "0.11.1"

[profile.bench]
debug = 0
codegen-units = 1