[package]
name = "concurrent"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["rlib", "dylib"]

[dependencies]
parking_lot = "0.11.1"
crossbeam-epoch = "0.8.0"
crossbeam-utils = "0.8.0"

[profile.release]
debug = 0